### ISSUE TITLE
Issue with creating a jupyter notebook 

### ISSUE THREAD

**Issue by NomiCentarix** [getzlab/rnaseqc#68]
Hello,
 
Can you please help me solve the below error which occur when I run the "Jupyter Notebooks" module?

I use _Python 3.9.5_.
I installed nbconvert with "pip3 install nbconvert"

The "Aggregation" and "Report" modules work without errors.

```
[NbConvertApp] Converting notebook notebook_res to notebook
[NbConvertApp] WARNING | Kernelspec name python3 cannot be found!
[NbConvertApp] ERROR | No such kernel named python3
Traceback (most recent call last):
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 385, in _async_start_kernel
    kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 38, in ensure_async
    return await obj
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 348, in _async_pre_start_kernel
    self.kernel_spec,
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 176, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 294, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
Traceback (most recent call last):
  File "/home/nomi/.local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/home/nomi/.local/lib/python3.9/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 588, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 551, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 479, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 189, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 206, in from_file
    return self.from_notebook_node(
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/exporters/notebook.py", line 35, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 146, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 335, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 85, in preprocess
    with self.setup_kernel():
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbclient/client.py", line 599, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "/home/nomi/.local/lib/python3.9/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nomi/.local/lib/python3.9/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nomi/.local/lib/python3.9/site-packages/nbclient/client.py", line 549, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "/home/nomi/.local/lib/python3.9/site-packages/nbclient/util.py", line 97, in ensure_async
    result = await obj
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 83, in wrapper
    raise e
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 385, in _async_start_kernel
    kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 38, in ensure_async
    return await obj
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 348, in _async_pre_start_kernel
    self.kernel_spec,
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 176, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/nomi/.local/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 294, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nomi/.local/lib/python3.9/site-packages/rnaseqc/create_notebook.py", line 58, in <module>
    subprocess.check_call('jupyter nbconvert --execute --inplace {}'.format(args.output.name), shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'jupyter nbconvert --execute --inplace notebook_res' returned non-zero exit status 1
```

**Comment by agraubert** [comment]
This looks like it could either be a bug with nbconvert, or maybe an issue with your jupyter environment. Try running `jupyter notebook` and see what kernels are listed in the top right of the browser window that opens

**Comment by NomiCentarix** [comment]
I get "Jupyter command `jupyter-notebook` not found."
I installed jupyter with this [tutorial ](https://speedysense.com/install-jupyter-notebook-on-ubuntu-20-04/) but maybe I have to add it to the path?

**Comment by agraubert** [comment]
It should already be on the path. I've never seen this issue where installing jupyter did not properly configure the sub-commands
